server:
  port: 8761
spring:
  #如果是本地配置config则需要添加该行
  profiles:
    active: native
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: eureka-server
  security:
    user:
      name: clf
      password: clf123
      roles: SUPERUSER
  cloud:
    config:
      server:
        #本地配置方式
        native:
          search-locations:
            - classpath:/config/user-server/
            - classpath:/config/netty-server/
            - classpath:/config/gateway-server/
            - classpath:/config/datasource-common/
            - classpath:/config/netty-common/
            - classpath:/config/redis-common/
        #git配置的方式
#        git:
#          uri: https://gitee.com/kvenclf/cloud-config.git
#          search-paths: repo1
#          username: "1256233771@qq.com"
#          password: "Qq771.com"
#        prefix: /config # 自定义的过滤前缀,避免在内嵌服务时对全部的url进行git的转发
#      label: master
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8761/eureka/
      instance:
        prefer-ip-address: true # 当猜测主机名时，服务器的IP地址应该在操作系统报告的主机名中使用
  server:
    peer-node-read-timeout-ms: 2000 #默认200ms间隔较短,避免peer端的注册未完成注册中心报错
management:
  endpoints:
    web:
      exposure:
        include: "*" # 暴露对应的刷新接口 /monitor 和 /actuator/bus-refresh