#应用维护
#启动shutdown模块
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: shutdown
      base-path: /uchain
  server:
    port: ${server.port}
    address: 127.0.0.1
  servlet:
    multipart:
      enabled: true
      # 设置文件大小限制  10MB
      max-file-size: 102400000
      # 设置总上传数据总大小 30MB
      max-request-size: 307200000
tmpFilePath: "/Users/mac/Downloads/tmp/"
